=== bigqdel/wydatki/wydatki.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Wydatki">
        <xs:complexType>
            <xs:sequence>
                <xs:element  maxOccurs="unbounded" name="Wydatek">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="DataDodania" type="xs:date" />
                            <xs:element name="Rachunek">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Paragon"/>
                                        <xs:enumeration value="Faktura"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Kategoria">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Jedzenie"/>
                                        <xs:enumeration value="SamochÃ³d"/>
                                        <xs:enumeration value="Rozrywka"/>
                                        <xs:enumeration value="Rachunki"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Waluta" type="xs:string" />
                            <xs:element name="Kwota" type="xs:decimal" />
                            <xs:element name="Data" type="xs:date" />
                            <xs:element name="Plik" type="xs:string" />
                        </xs:sequence>
                        
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== bigqdel/wydatki/wydatki.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="wydatki.xsl"?>
<Wydatki xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="wydatki.xsd">

	

<Wydatek><DataDodania>2019-05-11</DataDodania><Rachunek>Paragon</Rachunek><Kategoria>Jedzenie</Kategoria><Waluta>PLN</Waluta><Kwota>123</Kwota><Data>2019-05-01</Data><Plik>2019-05-11 215904.png</Plik></Wydatek><Wydatek><DataDodania>2019-05-11</DataDodania><Rachunek>Paragon</Rachunek><Kategoria>Rozrywka</Kategoria><Waluta>PLN</Waluta><Kwota>666.34</Kwota><Data>2019-05-01</Data><Plik>2019-05-11 215925.png</Plik></Wydatek><Wydatek><DataDodania>2019-05-11</DataDodania><Rachunek>Faktura</Rachunek><Kategoria>Rozrywka</Kategoria><Waluta>PLN</Waluta><Kwota>1123</Kwota><Data>2019-05-28</Data><Plik>2019-05-11 220012.png</Plik></Wydatek><Wydatek><DataDodania>2019-05-11</DataDodania><Rachunek>Faktura</Rachunek><Kategoria>Samoch&#243;d</Kategoria><Waluta>PLN</Waluta><Kwota>3345</Kwota><Data>2019-03-04</Data><Plik>2019-05-11 220044.png</Plik></Wydatek></Wydatki>
